[opener]
nvim = [
  { run = 'nvim "%s"', block = true, for = "unix", desc = "Neovim" }
]

vscode = [
  { run = 'code wait "%s"', block = true, for = "unix", desc = "VS Code" }
]

[open]
rules = [
  { mime = "text/*", use = ["nvim", "vscode", "reveal", "exif"] }
]
